# Generated by Django 3.1.2 on 2020-11-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descricao', models.TextField()),
                ('id_preco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preco.preco')),
            ],
        ),
    ]
