# Generated by Django 3.1.2 on 2020-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_catalogo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='descricao',
        ),
    ]
