# Generated by Django 3.1.2 on 2020-10-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_catalogo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='descricao',
            field=models.TextField(default='vazio'),
            preserve_default=False,
        ),
    ]
