# Generated by Django 3.1.2 on 2020-10-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
        ('catalogo', '0004_catalogo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='lote',
            field=models.ForeignKey(default='vazio', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='lote.lote'),
            preserve_default=False,
        ),
    ]
