# Generated by Django 3.1.2 on 2020-10-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_catalogo_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='lote',
        ),
    ]
